### ISSUE TITLE
version number from the output through $(naive -version) doesn't contain "-1" "-2" etc

### ISSUE THREAD

**Issue by cary-sas** [klzgrad/naiveproxy#336] opened 2022-10-09 16:50 UTC
I need use program to compare the versions between local binary and your github release, however I found the output from "$(naive -version)" by both binary from "v106.0.5249.91-1" ,"v106.0.5249.91-2" are same equal to "106.0.5249.91", how to distingwish the two version by local binary CLI ?

<img width="321" alt="image" src="https://user-images.githubusercontent.com/61653855/194769074-5ab89a3a-9464-4549-a0ce-0fd6dab23207.png">

**Comment by klzgrad** [comment] 2022-10-09 17:02
Duplicate of https://github.com/klzgrad/naiveproxy/issues/186#issuecomment-847034245

**Closed by klzgrad** 2022-10-09 17:02 UTC
