### ISSUE TITLE
Allow choosing IPv4 or IPv6 in client configuration

### ISSUE THREAD

**Issue by jwfang** [klzgrad/naiveproxy#631] opened 2024-03-13 14:56 UTC
My VPS have shitty connectivity/route via IPv4, but much better with IPv6. I want to finer control the IP version used.
BTW: I want to use both versions, IPv6 as primary and IPv4 as backup.

This can be workaround with DNS record for different IP versions, but it's ugly, not very elegant and cause management burden.

Can _navie_ have a -4 and -6 switch as most network tools do today ?

**Comment by klzgrad** [comment] 2024-03-16 14:49
Duplicate of https://github.com/klzgrad/naiveproxy/issues/330

**Closed by klzgrad** 2024-03-16 14:49 UTC
