### ISSUE TITLE
Please support the release version of the freebsd operating system

### ISSUE THREAD

**Issue by right0808** [klzgrad/naiveproxy#461] opened 2023-02-06 07:56 UTC
Please support the release version of the freebsd operating system.
thank you very much.

**Comment by Chilledheart** [comment] 2023-02-11 07:39
It should be straightforward if you can build it from a live freebsd os.
For cross-compiling, you can start with sysroot: http://ftp.freebsd.org/pub/FreeBSD/releases/amd64/13.0-RELEASE/base.txz

**Comment by klzgrad** [comment] 2023-02-19 04:33
Duplicate of #433.

**Closed by klzgrad** 2023-02-19 04:33 UTC
