### ISSUE TITLE
PartitionAlloc leaks memory on kernels without madvise

### ISSUE THREAD

**Issue by zhangbo8418** [klzgrad/naiveproxy#664] opened 2024-08-22 08:10 UTC
v128.0.6613.40-1 memory usage is too large

**Comment by zhangbo8418** [comment] 2024-08-30 13:46
> More detailed information is required.

I installed a transparent proxy on the router. After a few days, the memory exploded. It felt like there was a memory leak. . . .

**Comment by zhangbo8418** [comment] 2024-09-04 00:51
> More detailed information is required.

It may be caused by this optimization
https://github.com/klzgrad/naiveproxy/commit/d6391623e54c65d415b31b03b26712e959a115f5. Because I am a router, the memory is very small, and when multiple devices pass through the router, the memory usage of naiveproxy increases dramatically. It would be great if I could customize it through the configuration file. . . .

**Comment by Chilledheart** [comment] 2024-09-04 05:21
@zhangbo8418 for reference, latest curl use much larger http2 local window size aka 1000MiB, you can try curl in your device to download a large file in _http2_ method to see if your memory get exhausted. see https://github.com/curl/curl/commit/de4b0164f236dd81da92667c87b71422f2ce8aca.

**Comment by Chilledheart** [comment] 2024-09-04 05:23
PS you should use curl later than 8.1.0.

**Comment by zhangbo8418** [comment] 2024-09-04 07:00
> PS you should use curl later than 8.1.0.

curl 7.52.1 (mipsel-unknown-linux-gnu) libcurl/7.52.1 OpenSSL/1.0.2u zlib/1.2.8 libidn2/2.0.5 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.8.0 nghttp2/1.18.1 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

**Comment by Chilledheart** [comment] 2024-09-07 08:11
@zhangbo8418 either you should be able to compile naiveproxy without the patch you specified or you should be able to compile latest curl targetting on your device (recommend static build). If you are using openwrt, latest [curl] packages are available.

[curl]: https://openwrt.org/packages/pkgdata/curl

**Comment by Chilledheart** [comment] 2024-09-07 08:14
openwrt packages: https://downloads.openwrt.org/releases/23.05.4/packages

such as arm_cortex-a9:

https://downloads.openwrt.org/releases/23.05.4/packages/arm_cortex-a9/packages/curl_8.7.1-r1_arm_cortex-a9.ipk
https://downloads.openwrt.org/releases/23.05.4/packages/arm_cortex-a9/packages/libcurl4_8.7.1-r1_arm_cortex-a9.ipk
https://downloads.openwrt.org/releases/23.05.4/packages/arm_cortex-a9/packages/libcurl-gnutls4_8.7.1-1_arm_cortex-a9.ipk

**Comment by zhangbo8418** [comment] 2024-09-07 13:39
> openwrt packages: https://downloads.openwrt.org/releases/23.05.4/packages
> 
> such as arm_cortex-a9:
> 
> https://downloads.openwrt.org/releases/23.05.4/packages/arm_cortex-a9/packages/curl_8.7.1-r1_arm_cortex-a9.ipk https://downloads.openwrt.org/releases/23.05.4/packages/arm_cortex-a9/packages/libcurl4_8.7.1-r1_arm_cortex-a9.ipk https://downloads.openwrt.org/releases/23.05.4/packages/arm_cortex-a9/packages/libcurl-gnutls4_8.7.1-1_arm_cortex-a9.ipk


But my router is ubnt er-x, the CPU is mipsel, and the naive version I use is a statically compiled version.
![20240907213808](https://github.com/user-attachments/assets/b792f48f-3b15-49e2-944f-baa8970590dc)

**Comment by zhangbo8418** [comment] 2024-09-07 13:52
> @zhangbo8418 either you should be able to compile naiveproxy without [the patch you specified](https://github.com/klzgrad/naiveproxy/commit/d6391623e54c65d415b31b03b26712e959a115f5) or you should be able to compile latest curl targetting on your device (recommend static build). If you are using openwrt, latest [curl](https://openwrt.org/packages/pkgdata/curl) packages are available.

The memory will no
![20240907214947](https://github.com/user-attachments/assets/6384170f-7d96-4258-862d-748aff6da032)
t be freed it will keep increasing.

**Comment by zhangbo8418** [comment] 2024-09-07 13:53
> @zhangbo8418 either you should be able to compile naiveproxy without [the patch you specified](https://github.com/klzgrad/naiveproxy/commit/d6391623e54c65d415b31b03b26712e959a115f5) or you should be able to compile latest curl targetting on your device (recommend static build). If you are using openwrt, latest [curl](https://openwrt.org/packages/pkgdata/curl) packages are available.

The memory will not be freed it will keep increasing.
![20240907214947](https://github.com/user-attachments/assets/6f468004-b582-4d9c-bf27-3898b0f34da7)

**Comment by klzgrad** [comment] 2024-09-08 03:49
https://github.com/klzgrad/naiveproxy/releases/tag/v128.0.6613.40-2 I added `--http2-recv-window` so you can use `--http2-recv-window=6291456` to revert to previous window sizes. But I doubt memory use increase is caused by recv window size.

You should post a comparison of RES usage for v127, v128-1, v128-2 with `--http2-recv-window=6291456`.

**Comment by zhangbo8418** [comment] 2024-09-08 03:59
> v127, v128-1, v128-2

Thanks, I'll try it right away. In fact, the memory of v127, v128-1, and v128-2 will eventually explode, because the client will not release the memory if it does not pass naive, and the memory will only continue to increase. It is just that the growth is very fast after v127-3. Within 24 hours here It exploded and caused the router to crash. The growth of v127-2 was slower, about 4-5 days (of course, it is also related to the number of clients passing naive).

**Comment by zhangbo8418** [comment] 2024-09-08 04:13
This problem is common for direct terminal devices, but since the router is powered on 7*24, it becomes a more serious problem if the memory is not released.

**Comment by zhangbo8418** [comment] 2024-09-09 03:39
> https://github.com/klzgrad/naiveproxy/releases/tag/v128.0.6613.40-2 I added `--http2-recv-window` so you can use `--http2-recv-window=6291456` to revert to previous window sizes. But I doubt memory use increase is caused by recv window size.
> 
> You should post a comparison of RES usage for v127, v128-1, v128-2 with `--http2-recv-window=6291456`.

v128-2 just like this, the memory has been increasing slowly, but it still will not release the memory.

**Comment by zhangbo8418** [comment] 2024-09-09 03:58
> https://github.com/klzgrad/naiveproxy/releases/tag/v128.0.6613.40-2 I added `--http2-recv-window` so you can use `--http2-recv-window=6291456` to revert to previous window sizes. But I doubt memory use increase is caused by recv window size.
> 
> You should post a comparison of RES usage for v127, v128-1, v128-2 with `--http2-recv-window=6291456`.

v128-2 just like this, the memory has been increasing slowly, but it still will not release the memory.

Uploading lv1.mp4…

**Comment by zhangbo8418** [comment] 2024-09-09 04:08
> https://github.com/klzgrad/naiveproxy/releases/tag/v128.0.6613.40-2 I added `--http2-recv-window` so you can use `--http2-recv-window=6291456` to revert to previous window sizes. But I doubt memory use increase is caused by recv window size.
> 
> You should post a comparison of RES usage for v127, v128-1, v128-2 with `--http2-recv-window=6291456`.

v128-2 just like this, the memory has been increasing slowly, but it still will not release the memory.

https://github.com/user-attachments/assets/abf5452a-afd9-45ad-b098-0d40a82d8b8e

**Comment by Chilledheart** [comment] 2024-09-15 08:16
It seems the memory usage goes up quickly when you're closing the chrome windows (aka shuting down network connections). It is different story from http2 window size increase.

I don't know why it didn't recover the memory from closing network connections. It makes things harder to investigate. I guess something went wrong with PartitionAlloc or the connection pool but I don't have any proof.

Probably you need something like allocation profiler https://developer.chrome.com/docs/devtools/memory-problems/allocation-profiler to continue the investigation. But it is probably not available to the naive.

**Comment by Chilledheart** [comment] 2024-09-15 08:19
And because you're using static build, it might help to upgrade the openwrt SDK used to build. The newer SDK will bring newer libc library and that wil resolve some common bugs fixed in newer library.

**Comment by Chilledheart** [comment] 2024-09-15 08:24
And and orbit https://github.com/google/orbit is one of memory profilers I use to profile native C++ program. Hers is the document https://github.com/google/orbit/blob/main/documentation/DOCUMENTATION.md. You can start it and connect it remotely to see how your program allocs the memory.

And and and It will save your life if you can reproduce it in local linux system with glibc than your ubnt box.

**Comment by zhangbo8418** [comment] 2024-09-16 12:35
> This problem is common for direct terminal devices, but since the router is powered on 7*24, it becomes a more serious problem if the memory is not released.

Actually, this issue has minimal impact on direct terminal devices, but since routers operate 24/7, it becomes a severe problem if the memory cannot be released.

**Comment by zhangbo8418** [comment] 2024-09-16 14:21
> And and orbit https://github.com/google/orbit is one of memory profilers I use to profile native C++ program. Hers is the document https://github.com/google/orbit/blob/main/documentation/DOCUMENTATION.md. You can start it and connect it remotely to see how your program allocs the memory.
> 
> And and and It will save your life if you can reproduce it in local linux system with glibc than your ubnt box.

Actually, this issue has minimal impact on direct terminal devices, but since routers operate 24/7, it becomes a severe problem if the memory cannot be released.

**Comment by Chilledheart** [comment] 2024-09-19 01:57
> > And and orbit https://github.com/google/orbit is one of memory profilers I use to profile native C++ program. Hers is the document https://github.com/google/orbit/blob/main/documentation/DOCUMENTATION.md. You can start it and connect it remotely to see how your program allocs the memory.
> > And and and It will save your life if you can reproduce it in local linux system with glibc than your ubnt box.
> 
> Actually, this issue has minimal impact on direct terminal devices, but since routers operate 24/7, it becomes a severe problem if the memory cannot be released.

It is still worth to do the emulation. naive is expected to run smooth under low memory limit.

As far as I know, you can use docker to emulate the memory limit.

https://docs.docker.com/engine/containers/resource_constraints/#limit-a-containers-access-to-memory

For bwrap, it might be a bit complex due to the description from below link.

https://github.com/containers/bubblewrap/issues/233

**Comment by zhangbo8418** [comment] 2024-10-18 04:04
> I found the reason and the solution. I was using the openwrt-mipsel_24kc-static version. and I needed to modify the github workflow files build.yml. Find the following section :
> 
> * arch: mipsel_24kc-static
>   openwrt: "target=ramips subtarget=rt305x"
>   target_cpu: mipsel
>   extra: 'mips_arch_variant="r2" mips_float_abi="soft" build_static=true no_madvise_syscall=true'
> 
> and change **no_madvise_syscall=true** to **no_madvise_syscall=false**, then build it. I guess the author may have set no_madvise_syscall=true to maintain maximum compatibility, which results in RAM not being automatically adjusted, causing memory usage to continuously increase without being released. If your kernel version is later than Linux 2.2, in most cases it supports the madvise syscall. In this case, it's recommended to set no_madvise_syscall=false, which allows the system to automatically adjust naive's memory usage. If your system does not support the madvise_syscall function, use the following command: while true; do /root/naive --listen=redir://0.0.0.0:1080 --proxy=https://xxxxxx:xxxxxx@example.com; done, which will automatically restart naive after it exits due to an error.


Although my EdgeRouter kernel is 4.14.54, it cannot be used after I compiled it with no_madvise_syscall=true, alas. . . No solution?
![20241018120204](https://github.com/user-attachments/assets/152de1bd-d319-4e46-99ef-ecb0c971f9fb)

**Comment by hisuwj** [comment] 2024-10-18 07:28
The CPU I am using is the same as yours; it is the MT7621. The workflow file build.yml on GitHub should be modified to:
- arch: mipsel_24kc-static
            openwrt: "target=ramips subtarget=rt305x"
            target_cpu: mipsel
            extra: 'mips_arch_variant="r2" mips_float_abi="soft" build_static=true no_madvise_syscall=false'
![222222222](https://github.com/user-attachments/assets/b4907fb8-6a56-4dc3-847d-b1ea6ff2208e)

**Comment by hisuwj** [comment] 2024-10-18 07:29
> > I found the reason and the solution. I was using the openwrt-mipsel_24kc-static version. and I needed to modify the github workflow files build.yml. Find the following section :
> > 
> > * arch: mipsel_24kc-static
> >   openwrt: "target=ramips subtarget=rt305x"
> >   target_cpu: mipsel
> >   extra: 'mips_arch_variant="r2" mips_float_abi="soft" build_static=true no_madvise_syscall=true'
> > 
> > and change **no_madvise_syscall=true** to **no_madvise_syscall=false**, then build it. I guess the author may have set no_madvise_syscall=true to maintain maximum compatibility, which results in RAM not being automatically adjusted, causing memory usage to continuously increase without being released. If your kernel version is later than Linux 2.2, in most cases it supports the madvise syscall. In this case, it's recommended to set no_madvise_syscall=false, which allows the system to automatically adjust naive's memory usage. If your system does not support the madvise_syscall function, use the following command: while true; do /root/naive --listen=redir://0.0.0.0:1080 --proxy=https://xxxxxx:xxxxxx@example.com; done, which will automatically restart naive after it exits due to an error.
> 
> Although my EdgeRouter kernel is 4.14.54, it cannot be used after I compiled it with no_madvise_syscall=true, alas. . . No solution? ![20241018120204](https://private-user-images.githubusercontent.com/46797568/377716306-152de1bd-d319-4e46-99ef-ecb0c971f9fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMzYwNDYsIm5iZiI6MTcyOTIzNTc0NiwicGF0aCI6Ii80Njc5NzU2OC8zNzc3MTYzMDYtMTUyZGUxYmQtZDMxOS00ZTQ2LTk5ZWYtZWNiMGM5NzFmOWZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDA3MTU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MWYyODIxODgyMmE5NmY4Njc5YWIzYTkzYmM1MTIxZjdlZmIyODc5NTcyNGFjOWY5ZTZmYjRkY2U2Njc3OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TOtbg8asPO3L2Kqy5CzuwHHiUAowJn-HSdSJALNl8Xg)

The CPU I am using is the same as yours; it is the MT7621. The workflow file build.yml on GitHub should be modified to:
- arch: mipsel_24kc-static
            openwrt: "target=ramips subtarget=rt305x"
            target_cpu: mipsel
            extra: 'mips_arch_variant="r2" mips_float_abi="soft" build_static=true no_madvise_syscall=false'
![222222222](https://github.com/user-attachments/assets/b4907fb8-6a56-4dc3-847d-b1ea6ff2208e)

**Comment by zhangbo8418** [comment] 2024-10-18 09:59
> no_madvise_syscall=false


The compiled binary cannot be executed after changing it to no_madvise_syscall=false. I have tried it.

**Comment by klzgrad** [comment] 2024-10-18 10:28
If you build with `no_madvise_syscall=false`, it will call madvise. And if your kernel does not have madvise, it will crash.

What is this EdgeRouter kernel 4.14.54, I have no idea if it has madvise.

**Comment by hisuwj** [comment] 2024-10-18 10:36
> > no_madvise_syscall=false
> 
> The compiled binary cannot be executed after changing it to no_madvise_syscall=false. I have tried it.

That means your system kernel does not support the madvise_syscall, so you can only use the original static version released by the author (no_madvise_syscall=true).

As a temporary solution, you can manually limit the maximum memory usage of naive using the ulimit command to prevent it from consuming too much memory and affecting other programs. You can also use while true; do; done to make naive automatically restart after crashing when it reaches the memory limit.

The specific method is as follows. This is my configuration, and you can adjust it based on your machine's actual memory.

vi naive.sh
-------------------------------------------------------
ulimit -v 120000   # Adjust according to your system's actual memory
ulimit -m 90000    # Adjust according to your system's actual memory
while true; do
    /root/np/naive /root/np/config.json
done
-------------------------------------------------------
chmod 755 ./naive.sh
./naive.sh &

**Comment by zhangbo8418** [comment] 2024-10-18 11:00
> > > no_madvise_syscall=false
> > 
> > 
> > The compiled binary cannot be executed after changing it to no_madvise_syscall=false. I have tried it.
> 
> That means your system kernel does not support the madvise_syscall, so you can only use the original static version released by the author (no_madvise_syscall=true).
> 
> As a temporary solution, you can manually limit the maximum memory usage of naive using the ulimit command to prevent it from consuming too much memory and affecting other programs. You can also use while true; do; done to make naive automatically restart after crashing when it reaches the memory limit.
> 
> The specific method is as follows. This is my configuration, and you can adjust it based on your machine's actual memory.
> 
> ## vi naive.sh
> ## ulimit -v 120000 # Adjust according to your system's actual memory
> ulimit -m 90000 # Adjust according to your system's actual memory
> while true; do
> /root/np/naive /root/np/config.json
> done
> chmod 755 ./naive.sh ./naive.sh &

ulimit modifies virtual memory and has no use for physical memory. This is obviously a memory leak BUG. It will not release memory because the client disconnects.

**Comment by zhangbo8418** [comment] 2024-10-18 16:08
> If you build with `no_madvise_syscall=false`, it will call madvise. And if your kernel does not have madvise, it will crash.
> 
> What is this EdgeRouter kernel 4.14.54, I have no idea if it has madvise.
> 
> You need to provide your detail as to why your kernel does not support madvise, or there is no way to find the right solution.

[core-naive-29778-5.zip](https://github.com/user-attachments/files/17438054/core-naive-29778-5.zip)

**Comment by klzgrad** [comment] 2024-10-19 00:50
```
config ADVISE_SYSCALLS
        bool "Enable madvise/fadvise syscalls" if EXPERT
        default y
        help
          This option enables the madvise and fadvise syscalls, used by
          applications to advise the kernel about their future memory or file
          usage, improving performance. If building an embedded system where no
          applications use these syscalls, you can disable this option to save
          space.
```

It's possible the kernel builder saw this description and thought disabling this can save space.

OpenWrt only enabled this after https://github.com/openwrt/openwrt/commit/56342ee2bcbf9bf8918a01045471c7bb7faa1596 4.9 in 2017. https://patchwork.ozlabs.org/project/lede/patch/20171015000719.5143-1-rosenp@gmail.com/

It seems PartitionAlloc requires madvise to manage memory and without madvise it leaks memory. This means PartitionAlloc is fundamentally incompatible with kernel with CONFIG_ADVISE_SYSCALLS disabled.

You can check if your kernel is built with CONFIG_ADVISE_SYSCALLS in /proc/config.gz or /boot/config-*.

**Comment by zhangbo8418** [comment] 2024-10-19 01:33
> /proc/config.gz or /boot/config-*.

There is no /proc/config.gz or /boot/config-*., it is probably not packaged.

**Comment by klzgrad** [comment] 2024-10-19 04:11
| Build alternative  | Cons |
| ------------- | ------------- |
| use_partition_alloc=false use_allocator_shim=false  | Avoidable memory fragmentation, loss of performance and memory safety on kernels with CONFIG_ADVISE_SYSCALLS |
| use_partition_alloc=true no_madvise_syscall=false| Crash on kernels without CONFIG_ADVISE_SYSCALLS |
| use_partition_alloc=true no_madvise_syscall=true| Memory leaks on kernels without CONFIG_ADVISE_SYSCALLS |
| Multiple build variants| Too many builds, confusing |

Now I choose `use_partition_alloc=false use_allocator_shim=false` to make the static builds compatible with kernels without CONFIG_ADVISE_SYSCALLS, at the cost of its memory inefficiency on kernels with CONFIG_ADVISE_SYSCALLS, without introducing too many build variants.

See if https://github.com/klzgrad/naiveproxy/releases/tag/v130.0.6723.40-3 fixes memory leaks reported here.

**Comment by zhangbo8418** [comment] 2024-10-19 04:51
> Build alternative	Cons
> use_partition_alloc=false use_allocator_shim=false	Avoidable memory fragmentation, loss of performance and memory safety on kernels with CONFIG_ADVISE_SYSCALLS
> use_partition_alloc=true no_madvise_syscall=false	Crash on kernels without CONFIG_ADVISE_SYSCALLS
> use_partition_alloc=true no_madvise_syscall=true	Memory leaks on kernels without CONFIG_ADVISE_SYSCALLS
> Multiple build variants	Too many builds, confusing
> Now I choose `use_partition_alloc=false use_allocator_shim=false` to make the static builds compatible with kernels without CONFIG_ADVISE_SYSCALLS, at the cost of its memory inefficiency on kernels with CONFIG_ADVISE_SYSCALLS, without introducing too many build variants.
> 
> See if https://github.com/klzgrad/naiveproxy/releases/tag/v130.0.6723.40-3 fixes memory leaks reported here.

That's ok, at least the memory will be freed.

**Comment by klzgrad** [comment] 2024-10-19 08:15
That is not ok, because people with normal kernels get worse performance from the static builds.

**Comment by hisuwj** [comment] 2024-10-19 08:26
> That is not ok, because people with normal kernels get worse performance from the static builds.

My system kernel supports madvise. If I remove use_partition_alloc=false and use_allocator_shim=false from the GitHub workflow file, it shouldn't lead to memory inefficiency, right? madvise should still be callable, correct?

**Comment by klzgrad** [comment] 2024-10-19 08:32
> If I remove

The point of this discussion is that the user should be able to download easily usable binaries without having to build from source.

The static builds exist because some users have legacy non-OpenWrt embedded distros that do not work with the musl dependency requirement.

What is your distro, and why do you need a static build? @hisuwj

**Comment by hisuwj** [comment] 2024-10-19 08:47
> > If I remove
> 
> The point of this discussion is that the user should be able to download easily usable binaries without having to build from source.
> 
> The static builds exist because some users have legacy non-OpenWrt embedded distros that do not work with the musl dependency requirement.
> 
> What is your distro, and why do you need a static build? @hisuwj

My system version is openwrt-21.02.7. The support for musl time64 started after the openwrt-22.03.0 version. Therefore, the versions prior to openwrt-21.02.7 do not support musl time64, so I can only choose the static version.

**Comment by hisuwj** [comment] 2024-10-19 09:05
> > > If I remove
> > 
> > 
> > The point of this discussion is that the user should be able to download easily usable binaries without having to build from source.
> > The static builds exist because some users have legacy non-OpenWrt embedded distros that do not work with the musl dependency requirement.
> > What is your distro, and why do you need a static build? @hisuwj
> 
> My system version is openwrt-21.02.7. The support for musl time64 started after the openwrt-22.03.0 version. Therefore, the versions prior to openwrt-21.02.7 do not support musl time64, so I can only choose the static version.

The musl version in openwrt-21.02.7 is 1.1.24, and support for time64 began only after musl 1.2.0.

**Comment by zhangbo8418** [comment] 2024-10-20 01:48
> That is not ok, because people with normal kernels get worse performance from the static builds.

The memory leak issue returns in v130.0.6723.40-4.

https://github.com/user-attachments/assets/ab6a0b44-1d26-4b30-8bfa-01f3ae532ef7

**Comment by klzgrad** [comment] 2024-10-20 01:55
Ok, either of you have reported inaccurate information.

> returns in v130.0.6723.40-4

What does returns mean, the leak does not reproduce in a previous version?

v130.0.6723.40-4 does not use madvise and still leaks. If true, this claim

> set no_madvise_syscall=true to maintain maximum compatibility, which results in RAM not being automatically adjusted, causing memory usage to continuously increase without being released

is false.

**Comment by zhangbo8418** [comment] 2024-10-20 01:59
> Ok, either of you have reported inaccurate information.
> 
> > returns in v130.0.6723.40-4
> 
> What does returns mean, the leak does not reproduce in a previous version?
> 
> v130.0.6723.40-4 does not use madvise and still leaks. If true, this claim
> 
> > set no_madvise_syscall=true to maintain maximum compatibility, which results in RAM not being automatically adjusted, causing memory usage to continuously increase without being released
> 
> is false.


But it is true that memory can be released in version v130.0.6723.40-3, as shown in the video.

**Comment by klzgrad** [comment] 2024-10-20 04:37
I did some tests and there are no memory leaks over 10 connections each of which lasted for 60 seconds.

![naive 3](https://github.com/user-attachments/assets/f70456ad-c37a-4c5e-adb3-90f8b98b339f)
(Static build with OpenWrt 23)

![naive 4](https://github.com/user-attachments/assets/c4df8244-8def-43b8-89b1-def142ecf32d)
(Static build with OpenWrt 18)

You were seeing different eagerness of the musl allocator returning memory to the kernel, but it is no a memory leak.

But I agree for the static builds it's better to use newer musl libc.

**Comment by zhangbo8418** [comment] 2024-10-20 04:57
> I did some tests and there are no memory leaks over 10 connections each of which lasted for 60 seconds.
> 
> ![naive 3](https://private-user-images.githubusercontent.com/9764056/378151990-f70456ad-c37a-4c5e-adb3-90f8b98b339f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MDAxODAsIm5iZiI6MTcyOTM5OTg4MCwicGF0aCI6Ii85NzY0MDU2LzM3ODE1MTk5MC1mNzA0NTZhZC1jMzdhLTRjNWUtYWRiMy05MGY4Yjk4YjMzOWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjBUMDQ1MTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjQ3YTAxZjU1OTg1Nzg1YzE1MGRjNjA2OGEzMzc3NzE4ZThiMWQ0OTQ2M2YyYzAyODQ2MGRhZDliMmYxYjJiMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Jd753KomNlSRPWACmhjwc6aIu5_TXz64tXmpmsaCzpA) (Static build with OpenWrt 23)
> 
> ![naive 4](https://private-user-images.githubusercontent.com/9764056/378151995-c4df8244-8def-43b8-89b1-def142ecf32d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MDAxODAsIm5iZiI6MTcyOTM5OTg4MCwicGF0aCI6Ii85NzY0MDU2LzM3ODE1MTk5NS1jNGRmODI0NC04ZGVmLTQzYjgtODliMS1kZWYxNDJlY2YzMmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjBUMDQ1MTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzkzNzIwN2I5YTU2MTQ5N2M3ZWIzMjFmMmRiYmQ5YzhhMjgzNzI4Njc5ZmM0Y2MzNzkxZWYxNWExYmQ3NGM5ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.wSuQB09VRbgGPzK57teg57xEZVodQr0PpUSjyHQs25U) (Static build with OpenWrt 18)
> 
> You were seeing different eagerness of the musl allocator returning memory to the kernel, but it is no a memory leak.
> 
> But I agree for the static builds it's better to use newer musl libc.


What I want to talk about in the video is v130.0.6723.40-3. When I clicked to download (it may be that the number of connections under multi-threading caused the memory to increase rapidly, this is not the key), then the memory increased from about 16M to about 43M. After canceling the download, the memory immediately returned to about 16M. However, when I clicked download in v130.0.6723.40-4, the memory went from about 5M (memory occupied when just starting) to about 50M. When I canceled the download, the memory did not fall back and remained at about 50M. .

**Comment by klzgrad** [comment] 2024-10-20 05:01
I don't want to talk about your video. It is not a time-series plot, and it shows nothing about the nature of memory leak.

**Comment by zhangbo8418** [comment] 2024-10-20 05:05
> I don't want to talk about your video. It is not a time-series plot, and it shows nothing about the nature of memory leak.

The problem is that the memory is not released. It's strange. Does it take a long time to release it?

**Comment by klzgrad** [comment] 2024-10-20 05:07
The memory should not be released and that is not a problem. You don't release all memories back to kernel immediately after use because that is bad performance. There is no overall increase of memory usage over time which is the definition of memory leak.

**Comment by zhangbo8418** [comment] 2024-10-20 05:16
> The memory should not be released and that is not a problem. You don't release all memories back to kernel immediately after use because that is bad performance. There is no overall increase of memory usage over time which is the definition of memory leak.

Well, maybe I need more testing, maybe you are right, v130.0.6723.40-3 uses a newer toolchain and its memory was freed immediately after I canceled the download.

**Closed** 2024-10-20 05:31 UTC

**Comment by Chilledheart** [comment] 2024-10-28 01:26
And there is one place calling madvise besides partitionalloc, aka boringssl see https://github.com/klzgrad/naiveproxy/blob/master/src/third_party/boringssl/src/crypto/bcm_support.h#L31.

![image](https://github.com/user-attachments/assets/c8bbeebc-6838-48c6-8f14-c188fafce3c4)


You can patch it easily by:

![image](https://github.com/user-attachments/assets/288a19a7-6cb1-403e-83a9-b088ff4034b7)

**Comment by klzgrad** [comment] 2024-11-10 09:50
madvise in boringssl can be called without ill effects.
